# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ea0a6ac66dc5cfdbe351090cf9f927c2ef262d3d624634ee0c1d3e73fc522eed77afa9c34a238ef610c84f0c33e21afd84cf659e8cbb6dca00802473d950729

test:
  secret_key_base: 5508d939a95fd2dd50db83fa74c2ab26e82c75b026d88342ae5b476254a956995789d0337eb18d5bde5fa845b90d46f99056270830d504619db2842cd930082c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
